### ISSUE TITLE
Catalyst voting is not supported on this device. Your current version is 2.2.1 and the required version is 2.3.2

### ISSUE THREAD

**Issue by MarcelhodlD** [vacuumlabs/adalite#1027]
Hello,

When trying to activate the voting i receive this error:
Catalyst voting is not supported on this device. Your current version is 2.2.1 and the required version is 2.3.2
Anybody knows how i can update?

kind regards 
Marcel

**Comment by MichalPetro** [comment]
Hello,

you can check this guide https://adalite.medium.com/catalyst-voting-registration-on-adalite-71d975f75755

_Cardano Ledger app versions 2.3.2 and higher is needed in order to register your vote. In order to install app 2.3.2 you need Ledger firmware 2.0.0 or higher for Nano S or version 1.3.0 for Nano X. Both these updates can be done in Ledger Live > Manager section. If you don't see the option to update the firmware to 2.0.0, please re-install Ledger Live. Please note, you need to close Ledger Live before trying to connect to AdaLite._
