### ISSUE TITLE
Pop-up infinite loop for access via Trezor

### ISSUE THREAD

**Issue by surenders7** [vacuumlabs/adalite#1044]
Hello, please refer to below screenshot, the loop never gets closed. There is no passphrase for this account. 

<img width="1440" alt="Screen Shot 2021-06-17 at 7 15 48 AM" src="https://user-images.githubusercontent.com/44674420/122387743-2ecbe080-cf3d-11eb-9fb7-f90add638194.png">

**Comment by MichalPetro** [comment]
Hello,
there is a bug in Trezor that will be fixed in next release. What you can do now is:

Solution 1: disable passphrase prompt in Trezor Suite settings - Settings > Device > Passphrase > Turn Off

Solution 2: confirm blank passphrase 7-8 times and the Trezor will let you in to your account

Solution 3: downgrade the Trezor firmware 2.3.6

**Comment by surenders7** [comment]
Thanks a lot. Used Solution 2 to resolve the issue for now.
