### ISSUE TITLE
Nano X not recognised after ledger live update

### ISSUE THREAD

**Issue by Lykhes** [vacuumlabs/adalite#1050]
After updating Ledger live to version 1.3.0, it cannot unlock Adalite account. Tried different ways, but nothing works. Can somebody please help me. I need to access my account. Thanks.

It displays this message:

TransportError: Failed to sign with Ledger device: U2F OTHER_ERROR. Make sure other apps (e.g. Ledger Live) or websites interacting with your HW wallet are closed. Also make sure to use the latest available version of the Cardano app/firmware on your HW wallet and web browser.

**Comment by refi93** [comment]
Hi @Lykhes - what browser/OS are you trying it on? Are you sure you have the Cardano app open (i.e. the screen should be showing "Waiting for commands")? If this suggestion doesn't help, I'd suggest trying Google Chrome browser which supports other, more stable protocols (WebHID, instead of U2F) to interact with Ledger, so this could also help.

Finally, as the error message suggests, don't forget to close Ledger Live or other apps/website which could be interacting with your Ledger as only one app can be interacting with your Ledger at any time.

**Comment by marxenegls** [comment]
Yes, i had this issue too when i tried setting my nano x for the first time, i already had nano s, so i just had to import the seed, the remedy was to reinstall ledger-live on android too. I guess it depends on which host os you're on as to which usb drivers to use, i used WebUSB, without ledger-live, mind you the Cardano app was installed on device, i closed ledger-live and used chrome without extensions, approved the cardano app on dev, then got the 'waiting for commands', only after that I launched adalite's connector, and it worked, there's a 900 sec idle lock out in adalite if i'm not mistaken
