### ISSUE TITLE
Connect ledger NANO X with AdaLite  wallet 

### ISSUE THREAD

**Issue by NOVA-2021** [vacuumlabs/adalite#1066]
I can't seams to connect my Ledger nano X to my AdaLite in order to add come  coin

I keep having issues 

please help 

many thanks

**Comment by refi93** [comment]
Hi @NOVA-2021 please share more details, e.g. what browser/OS are you using and what prompts/errors do you see in Adalite/on your Ledger device.

General troubleshooting steps I can suggest:
1. make sure to close Ledger Live or other apps/websites that could be potentially interacting with your Ledger
2. make sure to select the Cardano app on your Ledger device
3. try a different browser, especially Firefox/Chrome as they work differently with Ledger so chances are whatever issue you have in one won't happen in the other

Here's the general guide on how to use Ledger with Adalite: https://github.com/vacuumlabs/adalite/wiki/Ledger-accessing-your-wallet

**Comment by marxenegls** [comment]
i had similar difficulty on win7, eventually i fixed it by enabling a few services, since i had previously set them to manual. 

portable device enumerator
upnp device host
plug & play
shell hardware detection 


i disabled browser extensions i.e (ublock) on chrome to be sure nothing hinders it connecting, i exited it from sandboxie and closed ledger-live too 
on Nano go into Cardano app - should see "waiting for commands" 
then tried it again with WebUSB 
and
it worked
