### ISSUE TITLE
ADALITE TRANSACTION ERROR WHEN ATTEMPTING STAKE WITHDRAWAL VIA LEDGER NANO X

### ISSUE THREAD

**Issue by perruno1** [vacuumlabs/adalite#1070]
![IMG_9075](https://user-images.githubusercontent.com/58156243/125950005-3b31b3a7-3267-42a9-b53a-b26dd9703e91.jpg)

Guys good morning; I've have been trying to withdrawal the 07/14 ADA rewards as usual but for some reason, I'm now getting this error.  This is when I'm using my Ledger Nano X.  Can you please look in to it.

Thanks,

FZ

**Comment by MichalPetro** [comment]
Hello,

There is a bug in rewards withdrawal affecting users who voted and are eligible for Catalyst Fund 4 rewards. These users are unable to withdraw their rewards. This should be fixed in the next epoch 279 starting on 20.7.2021

Also please note you don't have to withdraw rewards, they are automatically staked.

**Comment by perruno1** [comment]
Thanks Michal.  I appreciate your help.  Yesterday I went into the ADALITE Telegram group to find out what's up, but I'm under the impression that there are lots of scammers into that ADALITE Telegram group.  You ask one question and out of the blue I started to get Telegram Calls in a very insisting manner to the point in which I had to block the caller and even remove the app off my phone
