### ISSUE TITLE
Adalite sent Cardano to different address

### ISSUE THREAD

**Issue by eternalvela** [vacuumlabs/adalite#1126]
Good afternoon,

I sent 2546 ADA from coinbase to ADALITE (september 6th) using TREZOR T. I scanned the address instead of copying and pasting. The CARDANOs have been sent to a different address than what is showing on my ADALITE wallet.
How do i recover those ADAs?
TRansaction Hash 89d5b9cc8c586c0db16c80d9b816d3ecf65f28951985ed155cf8d5ef8ad686eb

sent to addr1q9vek5j95m9asjmpwuzfu7u2qsqg0xahwhsz99l0x9qrrh6q4adrl79rm80culxtke629r8kktq2u5nwdfes57tg9hhqulvsrf

Actual address
addr1qyrv5ut2v7aydxada79mxp8pzgsz7cskpjf3vuxwyly45f87nrkf2cd9a0s05kx456w4k0hh5uxj8tnr35hnc2jz4pxqynsur9

Any help is greatly appreciated.

**Comment by MichalPetro** [comment]
Hello,
In general, users have this issue because of one of the following:

1) The user initially created a mnemonic wallet and sent funds to the mnemonic wallet instead of the Trezor wallet. Are you sure that you initially didn’t create a software wallet? Didn’t you write down some mnemonic phrase when you were initially creating your wallet on AdaLite? If yes, try to access the wallet with this seed phrase.

2) Users are using passphrase protection. https://wiki.trezor.io/Passphrase
Please note, when using passphrase protection, if you enter an incorrect password, the device will open a completely different wallet.

3) Users have multiple HW wallets and trying to access funds on the wrong device.

**Comment by eternalvela** [comment]
Ok quite possible that I may have entered a wrong paraphrase.
How do I recover the coins that have been sent to a completely random address?

I do not know who approved and put in this logic. Instead of stopping the user to proceed further, the logic is actually penalizing the user who has put in a wrong pass phrase or whose account has been compromised.

Any help is greatly appreciated.

**Comment by refi93** [comment]
Unfortunately, the only way to retrieve the funds is to use the same passphrase that has been typed originally, there's no feasible way of retrieving funds from random addresses.

The passphrase feature on Trezor is an advanced feature deliberately made to not check for a "correct" passphrase to give users plausible deniability as mentioned in the wiki (https://wiki.trezor.io/Passphrase) and this is, unfortunately, the downside of it, and wallet clients such as Adalitearen't able to check their correctness either

**Comment by eternalvela** [comment]
Thank you
