### ISSUE TITLE
I

### ISSUE THREAD

**Issue by JAVITOCM** [vacuumlabs/adalite#1133]
Hi

I sent 198 ADA from Binance to ADALITE (september 13th) using TREZOR T. I scanned the address FROM TREZOR T and sended. The CARDANOs have been sent to a different address than what is showing on my ADALITE wallet.
How do i recover those ADAs?
TRansaction Hash 365caa357974ed9ceca64e4875dc5a9a51f227f0119e38d14343315162a8ecc2

sent to this address (never asked me about mnemonic phrase): addr1qy8rmawpju0fc3u3z92uza2p6ksusaarjnuptt42220lcl87tva36pyaqq7pxkvfngegm2ztey959xh4mt4zgrpvlkcq2t94tz

Actual address (asked me about mnemonic phrase and created)
addr1qy409uk63z8jgw7dak077zcpwv3c75ntcsu7vs0600x4g32hq43tmjssmj74shqz9dsr6qfzfqym04yfwmcqvqkrptrqgw8xed

Any help is greatly appreciated.

**Comment by MichalPetro** [comment]
In general, users have this issue because of one of the following:

- The user initially created a mnemonic wallet and sent funds to the mnemonic wallet instead of the Trezor wallet. Are you sure that you initially didn’t create a software wallet? Didn’t you write down some mnemonic phrase when you were initially creating your wallet on AdaLite? If yes, try to access the wallet with this seed phrase.

- Users are using passphrase protection. https://wiki.trezor.io/Passphrase
Please note, when using passphrase protection, if you enter an incorrect password, the device will open a completely different wallet.

- Users have multiple HW wallets and trying to access funds on the wrong device.
