### ISSUE TITLE
Wallet not rendering in browser after yarn start-server

### ISSUE THREAD

**Issue by TrevorBenson** [vacuumlabs/adalite#1140]
When starting adalite via `ADALITE_PORT=3000 yarn start-server` the browser gets a connection and then never renders anything except ERR_SSL_PROTOCOL_ERROR, making some adjustments to the SSL cert generation I was able to get the error to go away, but the window remains white indefinitely.

I decided to try `yarn cypress:dev`  and the browser rendered the wallet just fine. I changed the `app/cypress/.env.cypress` to disable the mock server. I was able to send transactions on the testnet and delegate to pools. Next I changed the explorer url and network from the .env.example mainnet values. Starting `yarn cypress:dev` connects to the mainnet, renders the wallet in the browser and shows proper mainnet balances.

1. Is the documentation out of date? 
2. Is there a known issue which would cause `yarn start-server` to not work?
2. Is there any danger to changing the values and using `yarn cypress:dev` instead?

Version 6.7.1

Thanks in advance for any assistance you can provide.

**Comment by refi93** [comment]
For running the app locally `yarn dev` mentioned in the section below is the easiest option to run the app and .env.template is configured for it to work without additional changes.

Another alternative would be to run `ADALITE_ENABLE_HTTPS=true yarn start-server` and that would include the self-signed certificates to the server and https://localhost:3000 will work fine then. It is not really meant to be run in production and that's why it was left out from the readme, but I guess it would be less confusing to put it there and add a clarifying note instead, so I just updated it, thanks for pointing it out
