### ISSUE TITLE
My wallet Ledger no connect Adalite.

### ISSUE THREAD

**Issue by Celsomp** [vacuumlabs/adalite#1154]
Hi, my digital Ledger wallet does not connect with Adalite, I have disabled ledger live (Mac and Mobile) and nothing.
I cannot access my wallet. Can anyone help? Thanks

![screenshot-adalite io-2021 09 28-10_32_17](https://user-images.githubusercontent.com/91532984/135064732-db79bf54-cedd-4b48-bdef-105d65f8cf3f.png)

**Comment by MichalPetro** [comment]
Hello,

can you check what is the version of your Ledger Cardano app? (open Cardano on Ledger device and check there). It should be 2.5.1 (or higher). Also, when accessing AdaLitem you should have your Cardano app open on the Ledger device.

**Comment by Celsomp** [comment]
Sorted out. However when I entered I didn't find my funds. I'm connected with Ledger and Adalite nothing, when I access the cardanoscan I find the back there. How do I solve this? Thanks.

**Comment by MichalPetro** [comment]
In general, users have this issue because of one of the following:

1) The user initially created a mnemonic wallet and sent funds to the mnemonic wallet instead of the Ledger wallet. Are you sure that you initially didn’t create a software wallet? Didn’t you write down some mnemonic phrase when you were initially creating your wallet on AdaLite? If yes, try to access the wallet with this seed phrase.

2) Users are using passphrase protection. https://support.ledger.com/hc/en-us/articles/115005214529-Advanced-passphrase-security
Please note, when using passphrase protection, if you enter an incorrect password, the device will open a completely different wallet.

3) Users have multiple HW wallets and trying to access funds on the wrong device.
