### ISSUE TITLE
ADALITE Missing rewards

### ISSUE THREAD

**Issue by lordmalzahar** [vacuumlabs/adalite#1158]
Dear Team, 

I would like to know if the missing rewards from staking in ADALITE are forever loss or will I recover it them?

Seems like a bug in the system is affecting rewards using Adalite staking, if so would be better staking in exchanges like Binance? 

I though ADAlite was safer than exchanges but it seems that I was wrong.

**Comment by xdzurman** [comment]
Hello,

your rewards balance is correct, it is unaffected by this bug. You did not lose anything and there is no need to worry. The issue is only with displaying the reward entries in the reward history and the only thing that may be affected is the CSV export functionality used for accounting purposes.

**Comment by lordmalzahar** [comment]
Dear xdzurman,

Thanks for the information! 
👌👍
