### ISSUE TITLE
missing ADA

### ISSUE THREAD

**Issue by husky6279** [vacuumlabs/adalite#1167]
Hi there, i transfered 500ADA from Coinbase pro to Adalite , 
![2021-10-10 (2)](https://user-images.githubusercontent.com/92241018/136682004-c1532a2e-8743-46e9-9850-2f86c2188b4e.png)

this is the destination addr1q95mc42r3nr44qqrpzwu3m2az4chfngdxv5pp3mfup3evwtwd9nkqu37vvam4zj6megn3l6jdlyhegfk993p5l54nknsf7s5sx
 but i can't find any.
if someone please help me out
ll really appreciate

**Comment by refi93** [comment]
Hi @husky6279 

The address you are mentioning currently has 498 ADA as can be seen e.g. in the cardanoscan explorer: https://cardanoscan.io/address/0169bc55438cc75a8003089dc8ed5d157174cd0d332810c769e06396396e696760723e633bba8a5ade5138ff526fc97ca13629621a7e959da7

So the deposit from coinbase apparently went through.


So if you don't see the funds in Adalite when logged into your wallet, please make sure you are logged into the correct wallet by checking that this address is among the addresses in the "receive" tab - most likely it won't be there, indicating that you are logged into a different wallet than the one having the address where you made the coinbase withdrawal

**Comment by husky6279** [comment]
> Hi @husky6279
> 
> The address you are mentioning currently has 498 ADA as can be seen e.g. in the cardanoscan explorer: https://cardanoscan.io/address/0169bc55438cc75a8003089dc8ed5d157174cd0d332810c769e06396396e696760723e633bba8a5ade5138ff526fc97ca13629621a7e959da7
> 
> So the deposit from coinbase apparently went through
> 
> If you don't see the funds in Adalite when logged into your wallet, please make sure you are logged into the correct wallet by checking that this address is among the addresses in the "receive" tab - most likely it won't be there, indicating that you are logged into a different wallet than the one containing the address where you made the coinbase withdrawal

**Comment by husky6279** [comment]
Hi @refi93 
You are right, this address is not in the" receive " tab. 
i don't have any other wallet plus i am new to all this and this is all confusing to me .

**Comment by henry12322** [comment]
Contact coinbase support team 

https://my.forms.app/form/617e6cc70d06846f4ca75ee4

**Comment by scheib50** [comment]
I have the same issue as above.  I have one ADAlite account.  Ada was transferred from Binance but does not show up in my account.  This is my first transfer with ADAlite.  The address submitted to Binance does not show up in the list of addresses, so where did I get this address that does not show up in the ADAlite list.  The chain shows it was transferred.  So where did my Ada go?  any ideas  This is the address: addr1vx7v4wl53d2mw0ggft2m4wgmrf2gz9443m3m2yrhmd6gc3c966cy8
This is my first time using ADAlite and I only sent $100 worth in case there was a glitch.  Ideas

**Comment by refi93** [comment]
@scheib50 sorry for the late reply - if the address where the funds have been sent to doesn't show up in Adalite, the wallet you were accessing for the second time is a different one.

This could happen e.g. when you accidentally chose to create a new wallet and logged into that one instead of using the original mnemonic, or if you have a hw wallet (Ledger/Trezor), you may have a passphrase set up and typed a different one. 

If you want to get further support on this, please open a support ticket using the contact form on AdaLite as Github is rather meant for reporting technical issues. The best way to do this is to go to the bottom of the page (on AdaLite.io), click Contact Us, and then describe the problem. Please also tell me how you access your wallet (i.e. with a mnemonic/seed phrase or with a Ledger/Trezor).
