### ISSUE TITLE
Unable to connect to Adalite with Trezor T, please help

### ISSUE THREAD

**Issue by Spider942321** [vacuumlabs/adalite#1240]
I'm currently trying to connect my Yoroi wallet that's connected to a Trezor Model T to Adalite but when I click "unlock with trezor" on the site, I get the prompt that says:

"TrezorError: Trezor operation failed, please make sure ad blockers are switched off for this site and you are using the latest version of Trezor firmware. Cannot read properties of null (reading 'postMessage')"

I saw a post earlier that's having a similar issue but there seems to be no solution yet. Thank you for your help.

**Comment by refi93** [comment]
Hi @Spider942321 , sorry for the delayed reply. Can you clarify what browser were you using? Are you able to successfully log into other web wallets such as https://myetherwallet.com ? I would suggest trying a different browser or using incognito mode, which should disable add-ons potentially interfering with Trezor

**Comment by Spider942321** [comment]
Thank you @refi93. I managed to get the wallet to connect to AdaLite, but now I'm having a different problem. 

This is the support email I've sent to both Yoroi and AdaLite and I'm currently trying to get it solved:

"- I made a wallet with a Trezor T on October 10 and I got the ZBEK-4968 wallet that I was able to delegate to a pool with
- I was then able to make another wallet with the same Trezor on October 20 and got JCLD-5639, which I didn't know at the time that it wasn't to happen like that.
- I put ADA into both wallets and was able to withdraw from JCLD-5639 normally with the Trezor.
- I was unable to redelegate or approve any transaction (withdraw, redelegate, claim rewards, etc.) on ZBEK-4968 with the same Trezor.
- I didn't activate the passphrase for the Trezor or spending password for Yoroi, so that shouldn't be a problem.

What I'm curious about is:

- How did Yoroi generate this new wallet (JCLD-5639) when I already made one with the same Trezor (ZBEK-4968)?
- Is it possible for me to switch to ZBEK-4968 as the default for this Trezor so that I can withdraw my money or is it just lost forever as it's now not connected to the Trezor that I have? When I tried to recover it on either Adalite or Yoroi I get (JCLD-5639) instead of (ZBEK-4968).

I am able to see the correct funds and transaction history on Cardanoscan for ZBEK-4968,
so I know the ADA and other tokens are there, but I can't access them."

This seems to be an issue for a number of other people as well, as I've been seeing forum posts like this one.
https://forum.trezor.io/t/problem-with-yoroi-ada-and-trezor-model-t/3714/2

Thank you again for your suggestions, and I did get it working by using incognito.

**Comment by MichalPetro** [comment]
Hello @Spider942321 , this is in 99.9% of cases caused by one of the following:

- The user initially created a mnemonic wallet and sent funds to the mnemonic wallet instead of the Trezor wallet. Are you sure that you initially didn’t create a software wallet? Didn’t you write down some mnemonic phrase when you were initially creating your wallet on AdaLite? If yes, try to access the wallet with this seed phrase.

- Users are using passphrase protection. https://wiki.trezor.io/Passphrase
Please note, when using passphrase protection, if you enter an incorrect password, the device will open a completely different wallet.

- Users have multiple HW wallets and trying to access funds on the wrong device.
