### ISSUE TITLE
Transaction rejected while signing. Failed to write the report.

### ISSUE THREAD

**Issue by TS7519** [vacuumlabs/adalite#1261]
I installed my Ledger Nano X following the instructions and then sent from Kraken ADA to ADAlite. The Nano X could not be verified. The ADA can no longer be sent back to Kraken. I get the error message Transaction rejected while signing. Failed to write the report. What can I do to send the ADA from ADAlite or verify the Nano X?
Thx in advance!

**Comment by goldieben** [comment]
Hi!

To start, please make sure your Ledger's firmware and Cardano app are fully up to date. You can do this from Ledger Live => Manager. Be sure to update the firmware first.

Sometimes, it's advisable to re-install Ledger Live by downloading it from their site, since the program's internal updater has been known to (very occasionally) display that you're running the latest firmware when in fact you aren't. Re-installing afresh will ensure that this isn't an issue.

Once that's done, be sure to close all programs (such as Ledger Live or an antivirus) that could interfere with the connection between your computer and the device. Finally, make sure the app is open and running (with the prompt 'waiting for commands' visible) when you connect.

If that doesn't work, try a different browser and, if that doesn't work, a different device/operating system if you can. If that fails, please contact me using the contact form at the bottom of AdaLite.io and we'll investigate further.

Best,
Ben
AdaLite Support Team
