### ISSUE TITLE
Signing pool Registration Cert. Unsupported transaction Era

### ISSUE THREAD

**Issue by christobear** [vacuumlabs/adalite#1268]
When trying to drop in a Registration certificated in adalite's advanced tab, there is the error shown below. 
"Parser error: Invalid transaction format. Unsupported transaction era, preferably use TxBodyMary era."

The registration certificate appears to be built correctly in the alonzo era.

**Comment by refi93** [comment]
Hi @christobear, as the error message suggests, HW wallets, unfortunately, don't support the alonzo-era format of transactions, so for the time being the only option is to build the transaction in cardano-cli specifying an older era, e.g. --mary-era

**Comment by GitHubSeattle** [comment]
Getting same comment from my stakepool owner:  the file I send him, that he uploads to Adalite.io (advanced tab) returns "unsupported transaction era, preferably use TxBodyMary era".  My understanding is that he is using a Trezor.

Has this been addressed by adalite yet?   

Getting errors with both suggested options:

-  when using "cardano-cli stake-pool registration-certificate...." that contains all the stakepool info my owner needs to review on adalite.io (like parameters --pool-pledge);  getting errors when adding "--mary-era" as a parameter 

-  when using "cardano-cli transaction build-raw..." that allows --mary-era as a parameter;  getting errors because you can't add parameters like --pool-pledge (so I'm not sure how using the adalite webpage for registering a stake pool would be utilized).
