### ISSUE TITLE
Transaction failed using Trezor

### ISSUE THREAD

**Issue by mjackson001** [vacuumlabs/adalite#251]
Trying to send a transaction and it's failed three times in a row.  No way to access the raw bytes to try to debug.  Device: Trezor T.

**Comment by mjackson001** [comment]
The error was: Transaction failed: Submitting the transaction into Cardano network failed.

**Comment by mjackson001** [comment]
Pulling up the console window it looks like there was a communication error with the server:
"Failed to load resource: the server responded with a status of 503 (Service Unavailable)"
api/txs/submit:1

**Comment by ppershing** [comment]
Hi Mark, thanks for reporting the issue.
This might be related to a recent bug in all block explorers based on IOHK code. Emurgo already fixed their own version (https://github.com/Emurgo/project-icarus-importer/pull/10/files) and we have to do the same. We  will let you know once our backend is updated so that you can check whether the problem persists.
