### ISSUE TITLE
Tidy up frontend dependencies

### ISSUE THREAD

**Issue by tomaskulich** [vacuumlabs/adalite#418]
- webpack should be dev dependency

- file-saver and unistore are quite small libs - I'd copy them to the project as they are (only the relevant parts of them)

- we're having multiple versions of babel-polyfill and babel-runtime installed (because some of our libs depend on it by themselves). I'd download the polyfill from CDN and configure it as external (thus forcing the same version for everyone). (see current webpack config for example of external dependencies).

Alternatively, you can keep using npmregistry and just force the one version such as:
https://stackoverflow.com/questions/40884485/force-dependency-to-use-specific-sub-dependency-version.

**Comment by refi93** [comment]
Regarding babel runtime I'm not sure about the long term effects of forcing one version, since it may lead to unforeseen and possibly hard to track down problems if one of the affected libraries (namely ledgerjs-hw-app-cardano and trezor-connect) gets updated which may be quite frequent given the firmware updates of Trezor/Ledger, and they may end up depending on a newer version of it, possibly ending up needing to keep two versions. @tomaskulich what do you think about it?

We already got rid of babel-polyfill in the develop branch.
