### ISSUE TITLE
redis password ?

### ISSUE THREAD

**Issue by beykery** [vacuumlabs/adalite#462]
what is the redis password config ?

**Comment by refi93** [comment]
@beykery you probably mean `REDIS_URL` (https://github.com/vacuumlabs/adalite/blob/0658737f94b875331139b3c491eb5b098cd5e3db/.env.example#L4).

It's an optional parameter and it's used on production to have basic stats about the count of unique visits and transaction count (not volume) per day: https://github.com/vacuumlabs/adalite/blob/develop/server/middlewares/stats.js Since the site is deployed on Heroku, the server is restarted every 24 hours and the local variable which stores the IPs to determine whether the current visit was a new one, gets cleared every day.
