### ISSUE TITLE
can't log in with Ledger Nano X.  Used to work.  doesn't see device now.

### ISSUE THREAD

**Issue by plentius** [vacuumlabs/adalite#464]

**Comment by plentius** [comment]
I forgot to mention that I'm running Windows 10.  A few days ago I successfully logged in to a Nano S and transferred some ADA to it.  A few days later I went back to verify that it was there because I wanted to move it to my new Nano X.  It was still there so I felt confident that I could now access it and transfer it when I needed to.  Today I tried connecting again and AdaLite did not find any recognizable devices, neither S nor X devices were recognized.  I checked those devices with Ledger Live and they are still working normally.  So what did I do wrong?

**Comment by refi93** [comment]
@plentius what browser are you using? We recently had to switch from U2F to WebUSB due to its sunsetting by Ledger devs (https://www.ledger.com/2019/05/17/windows-10-update-sunsetting-u2f-tunnel-transport-for-ledger-devices/)

As a temporary workaround while we figure out the problem, so you are not cut off (if it worked previously), here is the link to the staging  environment where we deployed the version with U2F: https://adalite-staging2.herokuapp.com

**Comment by ExpertBlueJay** [comment]
I just made this account to say I'm also having this issue with AdaLite. It was working perfectly fine before, which was not even a month ago I believe.  I have the Ledger Nano S running Windows 10 on the Brave browser, but have tried Firefox and Chrome.

I get this message when trying to access AdaLite from Brave and Firefox:  Error during wallet initialization: WebUSB support is needed for Ledger. Please use Chrome or Opera.

And on Chrome I get a pop up window that says no compatible devices found.

**Comment by refi93** [comment]
Thanks for your reports @ExpertBlueJay and @plentius ! For now, we are rolling back to U2F until we figure out what is the cause of the issues you are experiencing.

**Comment by ExpertBlueJay** [comment]
> Thanks for your reports @ExpertBlueJay and @plentius ! For now, we are rolling back adalite.io to U2F until we figure out what is the cause of the issues you are experiencing.

Thanks for the quick reply! I had tried the link you provided: [https://adalite-staging2.herokuapp.com](url)
and was able to access AdaLite and see my coins there. And [https://adalite.io/](url) Is working for me now as well, although both links are only working from Chrome but I'm happy I can atleast have access to the wallet. I hope it works for @plentius as well as anyone else who might be having this issue.

Thanks again!

**Comment by plentius** [comment]
Thanks guys.  I just got on my computer here and will try to login again
with your suggestions.  I appreciate the great response and the support
from both of you, @ExpertBlueJay and Rafael.

* <http://www.jonAdamson.com>* <http://www.JonAdamson.com>

**Comment by refi93** [comment]
Turns out a driver is needed for Windows for WebUSB (the new transport protocol) on Ledger to work properly. Here is the link to the tool that should provision the drivers needed: https://zadig.akeo.ie (choose Nano S (or X) interface 2 and winUSB driver) Since this process seems quite "cumbersome" and Ledger devs said they would implement autoprovisioning of the driver in the upcoming versions of the apps, we will stick for now to U2F first, i.e. the rollbacked state.
