### ISSUE TITLE
Feature Request: Add a browser HTML version to the Github

### ISSUE THREAD

**Issue by K2APacific** [vacuumlabs/adalite#476]
Can you please add a browser enabling file with, for example, an index.html file to the Github repository so that people can start Adalite from their browser while offline ? That way a wallet can be created offline in full safety (sort of like an offline paper wallet). I know people can just download the browser version from the internet site using "Save Page As" but that is not a safe option since malicious code could be inserted into the internet site. The Github site is safer for downloads. Thanks !

**Comment by refi93** [comment]
@K2APacific you may be able to download the wallet code and generate the wallet itself offline, but without access to the internet you won't be able to see the wallet balance and unspent outputs, therefore you won't be able to sign transactions offline which defeats the purpose.

We may do something similar to what myetherwallet does (https://kb.myetherwallet.com/posts/offline/offline_transaction/) but in case of Cardano it's not that straightforward since you don't have a single Cardano address per wallet but actually several, derived from a root public key, so it would likely involve a few more rounds of moving data between the online and offline wallet.

Offline mode is a feature we actually thought about (#304), but currently, we prioritize more hardware wallets since we believe those provide a comparable level of security and the user experience is significantly better.

**Comment by K2APacific** [comment]
Thanks for the prompt reply. Yes exactly, I was going to request offline signing of transactions after the ability to create a wallet offline. But one step at a time. I know you guys are busy.
