### ISSUE TITLE
Trezor T freezes during signing of send ADA

### ISSUE THREAD

**Issue by dcon22** [vacuumlabs/adalite#523]
Tried it multiple times, everything goes smoothly, I scroll through transaction data on device, hold to confirm, check box appears, but when I let go of screen it goes blank and your website/wallet stay still waiting for device..  so now my funds are stuck (I hope) on device.

**Comment by refi93** [comment]
On which browser did you experience this problem? Does the developer console contain some error? You may get a more verbose output if you try it on staging: https://adalite-staging.herokuapp.com/

**Comment by refi93** [comment]
Also, you can privately share with us (via contact form on the site) the raw transaction that you were about to submit (before signing) so we can analyze it. You can notice "raw transaction" option in the popup before confirming the transaction on AdaLite

**Comment by dcon22** [comment]
Chrome... not sure about developer console, don’t know what that is
actually.  I tried it on a different computer as well.. same result. Is
there a different browser you suggest? I can try again tonight however and
will use the staging link.

**Comment by refi93** [comment]
I would recommend trying Firefox though I doubt it would make a difference, but maybe. Also please let us know which version of Trezor firmware you have. You can open the developer console (developer tools) by pressing F12 and when you go to the "console" tab, you may see some error message while you confirm the transaction on Trezor which you can forward here as well.

**Comment by dcon22** [comment]
Whatever the latest version of Trezor is.. again not at home right now..
but I just updated like 2 days ago so.

**Comment by dcon22** [comment]
tried staging site.. no additional messages. I saved a copy of the console
log errors.. not sure if you want it. Trezor FW is 2.1.6

**Comment by refi93** [comment]
Yes, you can forward them, thanks. The raw transaction body would probably help us the most with reproducing the problem and finding out how to fix it - I'm attaching a screenshot of how to obtain it.

Since the raw transaction body contains your addresses (but not the signatures), please share it with us over email (adalite@vacuumlabs.com) so they are not publicly exposed. Please send it as a plain text, not as a screenshot.

![Screenshot 2019-10-11 at 09 33 56](https://user-images.githubusercontent.com/4980147/66633189-87949300-ec0a-11e9-850a-9dd194e1a657.png)

**Comment by refi93** [comment]
Also, supposing that it's a problem with Trezor not being able to build the transaction because it's too big (too many unspent outputs), you may try as a workaround to send a smaller amount and see if Trezor is able to process it.

But before that, please try sending the original amount and forward us the transaction body so we are able to reproduce and analyze the issue deeper.

**Comment by dcon22** [comment]
sorry for the late reply, I did just complete a transfer to a different
address for smaller amount with no problems.. not sure if it's the
result of recent firmware update from Trezor.. or something you did.. or
just that it was a different transaction.. but anyway...heres to smoother
sailing going forward.. Thanks.

**Comment by refi93** [comment]
You are welcome. If you experience the problem again, don't hesitate to contact us
