### ISSUE TITLE
Trezor Firmware 2.1.6 - Transaction Rejected While Signing with Trezor Model T

### ISSUE THREAD

**Issue by alanao** [vacuumlabs/adalite#530]
Cannot send large amount of ADA out of ADALite wallet, but test transaction of 200 ADA worked.
Recently updated to Trezor Firmware 2.1.6

Pop up error says

Transaction Error

Transaction rejected while signing: Firmware error

**Comment by alanao** [comment]
![Screen Shot 2019-11-14 at 16 37 20](https://user-images.githubusercontent.com/2922193/68902441-ed8aa380-06fd-11ea-81e7-1826b7394ab5.png)

**Comment by alanao** [comment]
Some additional information to help you resolve the issue sooner. I asked around my network if anyone else had the same problem and it seems that it works when sending batches of 10K or 20K ADA, but if amount is larger than 100K it gives the error. Perhaps a memory problem with the extra digit?

**Comment by alanao** [comment]
More testing details. sending 99999 ADA still gives the firmware error, but sending batches l of 36000 work.

**Comment by MichalPetro** [comment]
Hello Alano, this is a known issue caused by bad memory management and memory overflow on Trezor device. This is  not caused by ADA volume of the transaction, rather it is caused when you have too many utxo on transaction input side (we are even checking the utxos of the transactions that created utxos that are being used  in your transaction). 

So if you for instance received funds from exchange that sent it to you in a huge bulk transaction with many recipients (with many utxo) and you want to reuse the utxos from this transaction for creating a new transaction - this may cause memory overflow.

Currently this may be resolved just like you did - by sending smaller amounts (therefore using less utxo inputs). 

This issue should be completely resolved when Shelley will be launched on main-net and we update the Trezor firmware to support Shelley as the witnesses in Shelley will contain transaction amount and therefore we wont need to "manually" calculate it from the utxo.
