### ISSUE TITLE
mnemonic length and address format

### ISSUE THREAD

**Issue by roccomuso** [vacuumlabs/adalite#583]
Why a 12 words mnemonic generates old format (Daedalus-like) address instead of new one?

**Comment by refi93** [comment]
Because 12-word mnemonics are used by Daedalus and 15-word by Yoroi. Therefore generating new (i.e. Yoroi) addresses from 12-word mnemonics would be a scheme not used by any official wallet. More on cross-wallet compatibility in the [FAQ](https://github.com/vacuumlabs/adalite/wiki/AdaLite-FAQ#compatibility-with-other-wallets)
