### ISSUE TITLE
Shelley / wallet + Staking questions 

### ISSUE THREAD

**Issue by boullinaise** [vacuumlabs/adalite#612]
As an end user will I have to do anything to my Lite / Ledger combo to maintain my ADA balance?

Any news regarding staking - will I be able to stake using Ada Lite / ledger or will we have to Daedalus?

Thanks from a non programmer

**Comment by MichalPetro** [comment]
Hi, currently the Cardano Shelley hard-fork that will enable staking is planned for early August but this date may be postponed. We will do our best to provide full Shelley functionalities since day 1 of the hard fork and it is very likely that we will manage to do this.

There will be no action needed from the users. You dont have to be worried about our Shelley compatibility because you can always easily open your Ledger wallet with any other Cardano wallet supporting Ledger (currently Yoroi, Daedalus very soon)
