### ISSUE TITLE
Transaction failed protocol: TransactionRejected

### ISSUE THREAD

**Issue by 1044740162** [vacuumlabs/adalite#617]
When I finished broadcasting the packaged transaction to the mainnet locally, I got this error 
```bash
Transaction validation error: Error: Tx cb0577544098c137c0871a658a237a8922b0f6a52746cf689325bb5fbef61bf9 already exists. (Network response: Transaction failed protocol: TransactionRejected)'.
```
 But I checked the blockchain and there is no Tx

**Comment by 1044740162** [comment]
When I changed the protocolMagic to 7648240731,
I got the following error again
```bash
'Transaction validation error: Error: Tx cb0577544098c137c0871a658a237a8922b0f6a52746cf689325bb5fbef61bf9 already exists. (Network response: Transaction failed verification: BadTxWitness)'

**Comment by refi93** [comment]
Yes, the transaction did not make it to the blockchain, but was recorded as "failed" in our DB, that's why you see that the transaction already exists. Anyway, the backend tries to resubmit it even though it appears to have failed in the past and that's why you see the second error as well ("bad tx witness")

Source code with the context: https://github.com/vacuumlabs/adalite-importer/blob/master-shelley/src/api/txs.js#L56

**Comment by 1044740162** [comment]
Thanks for your help, I have successfully solved this problem.
