### ISSUE TITLE
Ledger doesnt work

### ISSUE THREAD

**Issue by thissystemsucks** [vacuumlabs/adalite#644]
so i bought yesterday and decided to use adalite to hold my ADA. so yesterday i transfered it with my ledger to adalite and everything went fine, i saw the ADA on the website. 

today i try to login to adalite and none of the logins are working now when i loging to cardano on ledger. it just sits there, and the ledger says its waiting for command. i feel like i just got screwed cause i dont have access to my money, yet it worked yesterday to take my money.

i now updated my firmware on ledger to 1.2.4-1 and my windows 10 operating systems is version 1903 and is updated. it still isnt working. if i try to move the screen to the side, it just says are you there in a minute and basically stops trying to work. its  infuriating!!!

any help would be appreciated!!

**Comment by thissystemsucks** [comment]
TransportError: Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE

**Comment by thissystemsucks** [comment]
it says touch your security key on screen until it eventually crashes. ive tried to hook it up to my phone and do it that way via bluetooth, but im having trouble doing that also just connecting via bluetooth.

**Comment by MichalPetro** [comment]
Sorry to hear that you are having issues. First of all - the funds are not stored on AdaLite but on Ledger so there is no need to worry that we screwed you because we have no access to them.

This issue is occasionally happening on some Windows versions (probably with some specific browser version combinations). There are a few steps you should try to make in order to resolve:

- Ignore the "Touch your security screen" window - **don't close it,** just move it away and try to continue interacting with AdaLite.

- Make sure that you have turned off Windows Defender and all anti-virus and anti-malware software

- Try different browsers (Chrome, Brave, Firefox)

- If nothing helps you can try to access your wallet with Yoroi wallet Chrome extension https://chrome.google.com/webstore/detail/yoroi/ffnbelfdoeiohenkjibnmadjiehjhajb

-

**Comment by thissystemsucks** [comment]
thank you for replying, unfortunately none of those options worked for me. i turned off 2 firewalls, i tried to use it through chrome and edge. ill download firefox in a few and try it that way. it still just says "are you there" or "touch the security". when i try to click outside the box my computer just does the bling sound and basically doesnt allow me to do anything until i X out of the little connection box that pops up. i also tried using YOROI and a similiar thing happens; it just cancels as soon as i hit nano ledger and says that "the operation was cancelled by the user.

i had high hopes for those fixes but im still stuck

**Comment by thissystemsucks** [comment]
i got it to work with yoroi through google chrome extension! thank you!!!!!!!! im just happy i can see it and can access it, thank you Michal!
