### ISSUE TITLE
Is it will support 12-mnemonic  ？ 

### ISSUE THREAD

**Issue by bulingTang** [vacuumlabs/adalite#677]
hi , is it will support 12-Mnemonic, i try to set the ADALITE_CARDANO_VERSION to byron , but it doesn`t work well . and i set the 
```
const guessDerivationSchemeFromMnemonic = (mnemonic) => {
  if (ADALITE_CONFIG.ADALITE_CARDANO_VERSION === 'shelley') {
    return derivationSchemes.v2 //TODO: v1 should have been abandoned in shelley (?)
  }
  return mnemonic.split(' ').length === 12 ? derivationSchemes.v1 : derivationSchemes.v2
}
```
 to 
```
const guessDerivationSchemeFromMnemonic = (mnemonic) => {
  return mnemonic.split(' ').length === 12 ? derivationSchemes.v1 : derivationSchemes.v2
}
```
and it generate signTx but when boradcast , server return 
` ApplyTxError [LedgerFailure (UtxowFailure (MissingVKeyWitnessesUTXOW (WitHashes (fromList [KeyHash \da608fc5ba694d4d248cbf9941f8783db86c7bf94a942cd97a98c13f\]))))`
can you help me ?

**Comment by MichalPetro** [comment]
Hello,

We dont plan support for 12 words mnemonic. These users need to download and convert using Daedalus. Please create issue on GitHub for any development / devops related problems.

Michal

**Comment by bulingTang** [comment]
ok, thank you

**Comment by MichalPetro** [comment]
Dear AdaLite user,

you recently contacted us regarding the possibility to access wallets represented by 12-word mnemonics. I would like to inform you that this feature is back on AdaLite.

Please note, due to some inconsistencies between 12-words mnemonic implementations between different wallets, we possibly may not be able to open your wallet.

We can guarantee that this will work only for people that created 12-word wallets on AdaLite back in 2018 and never used this passphrase with any other wallet but AdaLite.

After logging in you will see a warning that this wallet doesn't provide all Shelley features (such as staking) and a guide on how to create a new 15-words wallet and migrate your funds to it.

It will be great to hear from you if this helped to solve your problem.

Best regards,
Michal
