### ISSUE TITLE
Accessing Cardano wallet using Trezor

### ISSUE THREAD

**Issue by captcreo** [vacuumlabs/adalite#692]
Hello, I have a mnemonic phrase of twelve words to access my cardano wallet using a trezor 1. I tried accessing it today and was redirected to adalite wallet that was asking for a fifteen-word phrase. Is this because of the new update? How can I access my wallet now?

**Comment by MichalPetro** [comment]
Hello,

trezor one doesnt work with Adalite. Where you have those 12 words seed from? You can recover 12 word seeds with daedaluswallet.io

**Comment by refi93** [comment]
Also probably an obvious note - please make sure to follow Trezor security best practices: https://wiki.trezor.io/User_manual:Security_best_practices and never insert your Trezor recovery phrase on any website/software even if you trust it as this defeats the security with which your Trezor shields the recovery seed from the outside world.

If you inserted your 12-word mnemonic in the past directly into adalite.io and you have funds there you can indeed use Daedalus to access those funds but we would advise you to set up a new recovery seed on your Trezor ASAP and move all the funds (even non-cardano ones) there as this means that your 12-word mnemonic was exposed to the outside world which is exactly the scenario that your Trezor is otherwise protecting you against.
