### ISSUE TITLE
Cannot submit signedBody by /api/v2/txs/signed

### ISSUE THREAD

**Issue by IMKAIER** [vacuumlabs/adalite#697]
I tried to submit  signedBody through transactionSubmitter.js 
 but  response status 400 bad request
please help thanks

**Comment by MichalPetro** [comment]
Hello, the general answer is that the request should comply with this code https://github.com/vacuumlabs/adalite/blob/develop-shelley/server/transactionSubmitter.js So you should include both tx body and tx hash. Also, you should check that you are building the transaction correctly by researching how to build transactions in Shelley.

Due to multiple reasons, we currently adopted a doctrine not to support any integration efforts from 3rd parties unless we know who we are dealing with and what is the purpose of re-using our code. If you need additional support, please state your business - what are your plans with AdaLite code. Feel free to do so by sending us email to adalite (at) vacuumlabs dot com if you are not comfortable doing it publicly.
