### ISSUE TITLE
Staked ADA did not move

### ISSUE THREAD

**Issue by Nats2010** [vacuumlabs/adalite#771]
I staked ADA, but it did not move to the staking pool..
![image](https://user-images.githubusercontent.com/76252893/102690409-eb065180-420d-11eb-8d9e-9b2056ffe65f.png)

**Comment by refi93** [comment]
Hi @Nats2010 could you please share the hash of the transaction and can you check in your browser history whether you actually visited https://adalite.io?

**Comment by refi93** [comment]
As far as we were able to match the transactions with the timestamps, it seems to have been a standard spending transaction: https://adapools.org/transactions/ea63cf7d1a72ed394c53d87698d7763f8abdae2d1b7e00238f51f9456b4640b6 - what guide/advice did you follow to stake your funds, and as pointed out above, can you check what website you used to stake your funds?

**Comment by Nats2010** [comment]
Hi, I used the site www.adalite.io <http://www.adalite.io> .

When I go to Adapools.org, I get the below:Is this correct?..is it staked?

**Comment by refi93** [comment]
Can you please post again, what you see on adapools? It doesn't seem to have arrived. But based on the transactions we matched with the timestamps in your screenshot (https://cardanoscan.io/transaction/ea63cf7d1a72ed394c53d87698d7763f8abdae2d1b7e00238f51f9456b4640b6) your funds are unfortunately not staked at all, they have been just sent to another address, namely addr1q8ndwl05ksnnvh7uswfupgq2mtqdkrw43j9nj5rqw0lr8pk7tgee0lk8ywd2ks2fukqxv0ytqj75wwqeuqkx3g9m9jesntjvgk .

Here is a link to a blog article explaining how to stake properly through Adalite: https://adapointpool.medium.com/how-to-delegate-stake-your-ada-on-shelley-with-ledger-nano-s-x-e6363a9c9050

**Comment by Nats2010** [comment]
Can you explain how I can retrieve those funds? 
--
Sent from myMail for Android Sunday, 20 December 2020, 05:06PM +02:00 from Rafael Korbaš  notifications@github.com :

**Comment by refi93** [comment]
Unless the destination address `addr1q8ndwl05ksnnvh7uswfupgq2mtqdkrw43j9nj5rqw0lr8pk7tgee0lk8ywd2ks2fukqxv0ytqj75wwqeuqkx3g9m9jesntjvgk` of the funds belongs to you, unfortunately, there's no way to retrieve the funds.

Can you please tell us what stake pool were you trying to delegate to and where did you get the instructions to do so? If the instructions told you that in order to delegate somewhere you need to send the funds somewhere else, are scams. Also, can you please double-check in your browser history that on December 15th, you were performing the transaction from https://adalite.io and not from an even slightly misspelled URL, like `adaiite  .io`, `ada-lite  .io` `adalite  .com`, `adaliite  .io` - such sites are scams, as we are warning on https://adalite.io landing page and using them results in loss funds.
