### ISSUE TITLE
Reset Ledger with new seed, still seeing old wallet

### ISSUE THREAD

**Issue by ekatchour** [vacuumlabs/adalite#818]
Steps:
- initialize Ledger wallet, install Cardano app, Litecoin app, deposit 1 LTC
- access Ledger wallet via AdaLite, deposit 1 ADA
- create new Exodus Wallet, record 12 word passphrase (note that this is different wallet)
- deposit 2 ADA, 2 LTC to the Exodus wallet
- now you have 2 wallets with different amounts
- reset Ledger with the same 12 word passphrase as Exodus
- reset Ledger Live, re-sync with Ledger again, install Cardano app, Litecoin app 
- now your Ledger is matching Exodus, you can confirm by seeing 2 LTC instead of 1.
- access Ledger wallet via AdaLite
Expected result: 
- you should see the new wallet with 2 ADA that is same as one on Exodus since you are using same passphrase
Actual result: 
- you are still seeing the old wallet with 1 ADA

**Comment by ppershing** [comment]
> reset Ledger with the same 12 word passphrase as Exodus
Unfortunately, hardware wallets does not necessarily derive addresses the same way as software wallets. The problem is compounded by the fact that Cardano (as opposed to BTC&BTC-like currencies) use a *different* derivation technique but many multi-currency wallets just ignore the fact. This can lead to a situation that the same mnemonic on exodus and ledger gives equal BTC address but different ADA address.

**Comment by refi93** [comment]
I'd add here is a summarization of how Cardano derivation schemes (techniques) vary across different platforms https://github.com/cardano-foundation/CIPs/blob/master/CIP-0003/CIP-0003.md
