### ISSUE TITLE
Issue with Buy/Sell with Ledger Nano S

### ISSUE THREAD

**Issue by knewbee333** [vacuumlabs/adalite#853]
Hello,

I saw that it is possible to exchange cryptocurrencies to ADA via Coinswitch. I have my Ledger Nano S paired, however, when I go to exchange cryptocurrency (in this case XLM) to ADA, I put in my receiving address and get the error: "Invalid ADA address". 

I have tried a few of the valid receiving addresses but I still get the same error. My addresses have the prefix "addr1" if that helps.

Thank you

**Comment by refi93** [comment]
Hi @knewbee333 Thanks for notifying us, we forwarded the report to our exchange partner (Coinswitch) to fix it. The issue seems specific to XLM->ADA switch as e.g. BTC->ADA validates the Cardano address properly. While the issue gets fixed, we'd recommend you to exchange your XLM for ADA with another provider you trust.

**Comment by refi93** [comment]
XLM -> ADA switch has been fixed on Coinswitch's side and no longer seems to fail with base addresses
