### ISSUE TITLE
ADALITE LEDGER LOGIN NOT WORKING

### ISSUE THREAD

**Issue by bobbydean106** [vacuumlabs/adalite#882]
I repeatedly get this message:

ServerError: Our servers are probably down. Please try again later and if the problem persists, contact us.

What's going on?

**Comment by refi93** [comment]
@bobbydean106 Sorry for the inconvenience, this was a temporary outage caused by the recent epoch boundary which resulted in our infrastructure powered by cardano-db-sync to significantly slow down and our servers being disabled to prevent them from serving stale data.

Our servers are up again and we are awaiting the next stable release of cardano-db-sync where this known issue should be fixed or at least significantly reduced: https://github.com/input-output-hk/cardano-db-sync/issues/478

**Comment by timdug** [comment]
I am not able to login. I need access.When can I expect a fix? 
Here is my message. I have the latest version of the app and latest firmware for Ledger and ledger LIVE. 
TransportError: Failed to sign with Ledger device: U2F DEVICE_INELIGIBLE.If you are using a hardware wallet, please make sure you are using the latest version of the Cardano application.

**Comment by erikd** [comment]
Just to be clear, the current slowdown in `db-sync` at the epoch boundary is up to about 10 minutes. I will check that at the end of epoch 253 which happens in about 45 minutes from now.

**Comment by refi93** [comment]
@timdug U2F issues with Ledger are unfortunately caused by operating system policies which cannot really be influenced. You would likely have the same issue with MyEtherwallet and the ethereum app if you try.

What usually helps is using Google Chrome browser and using the "Connect with WebUSB" functionality (the button bellow "Unlock with Ledger"). To make WebUSB work properly on Windows you may need to replace your driver using a 3rd party tool called Zadig - here is a guide by ShapeShift: https://shapeshift.zendesk.com/hc/en-us/articles/360011307520-Replacing-Your-Driver-Using-Zadig - upon launching the .exe choose Nano S/X interface 2 and winUSB driver.

We'll improve the troubleshooting suggestion you've seen for that error to help users get unstuck
