### ISSUE TITLE
Error loading wallet

### ISSUE THREAD

**Issue by perevista** [vacuumlabs/adalite#886]
I get this when trying to use Ada Lite with Trezor Model T:
ServerError: Our servers are probably down. Please try again later and if the problem persists, contact us.

Any ideas? Thanks.

**Comment by refi93** [comment]
@perevista Sorry for the inconvenience, this was a temporary outage caused by the recent epoch boundary which resulted in our infrastructure powered by cardano-db-sync to significantly slow down and our servers being automatically disabled to prevent them from serving stale data.

Our servers are up again and we are awaiting the next stable release of cardano-db-sync where this known issue should be fixed or at least significantly reduced: https://github.com/input-output-hk/cardano-db-sync/issues/478
